import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <header className={styles.header}>
                <h2>Header template</h2>
            </header>

            <main className={styles.main}>
                <h2>Main template</h2>
            </main>

            <footer className={styles.footer}>
                <h2>Footer template</h2>
            </footer>
        </div>
    );
}
